### ISSUE TITLE
Dynamic sheet doesn't update because of this plugin

### ISSUE THREAD

**Issue by iamstarkov** [iamstarkov/jss-increase-specificity#2] opened 2017-06-28 11:57 UTC
> Originally reported by @mistadikay in https://github.com/iamstarkov/jss-increase-id-specificity/issues/3  
> participators: @mistadikay, @kof

Hey!

I'm using `react-jss` with rules like:
```js
borderColor: ({ isValid }) => (isValid ? '#a5a5a5' : '#f00')
```

When `isValid` prop changes I can see that this function executes and returned value is correct, but the sheet doesn't update and visually border-color stays the same.

While debugging this issue I found out that this plugin was the problem, in particular [this string](https://github.com/iamstarkov/jss-increase-id-specificity/blob/master/index.js#L18) in `onProcessSheet` hook:
```js
rule.selectorText = prefix + rule.selectorText;
```

My questions are more to @kof I guess:
1) what is the correct way to change selector (assuming that the one described above is incorrect) to make dynamic sheets work?
2) could it be maybe connected with [this issue](https://github.com/cssinjs/react-jss/issues/94)?

Any help appreciated, thanks.

**Comment by iamstarkov** [comment] 2017-06-28 12:19
published as `jss-increase-specificity@0.2.0`

**Comment by mistadikay** [comment] 2017-07-22 08:39
The problem still persists. Updated reproducible case with `jss@8` and `react-jss@7`:
https://www.webpackbin.com/bins/-KpdPv8lAXfOMcVxO83V

**Comment by iamstarkov** [comment] 2017-07-24 10:11
that is interesting, i'll take a look

**Comment by mistadikay** [comment] 2017-07-31 11:43
apparently the bug can be reproduced even without this plugin. I just manually put the prefix:
```js
input: {
  ':not(#\\20)&': {
    borderColor: ({ isValid }) => isValid ? '#ccc' : '#f00'
  }
}
```

And border color does not update on `isValid` prop change. Any ideas why @kof?

Updated example:
https://www.webpackbin.com/bins/-KqNQW0EgULbR0SiYk8Z

**Comment by kof** [comment] 2017-07-31 11:45
Not from looking at it, there are too many dependencies  involved. Can you reproduce it with jss core only? Ideally submit a failing test?

**Comment by kof** [comment] 2017-07-31 11:46
as you are using ampersand, it might be also jss-nested fault

**Comment by mistadikay** [comment] 2017-07-31 11:58
Removed everything except `jss-nested` and `react-jss` — not sure how to reproduce it without them: [https://www.webpackbin.com/bins/-KqNVNfzLuuYxwDi5cY_](https://www.webpackbin.com/bins/-KqNVNfzLuuYxwDi5cY_)

**Comment by kof** [comment] 2017-07-31 12:00
sheet.update(data) is the method which is called by react-jss

**Comment by mistadikay** [comment] 2017-07-31 12:18
Removed `react-jss`: [https://www.webpackbin.com/bins/-KqNVNfzLuuYxwDi5cY_](https://www.webpackbin.com/bins/-KqNVNfzLuuYxwDi5cY_) Nor sure if I'm updating correctly:
```js
sheet.update({ isValid });
const { classes } = sheet.attach();
```

**Comment by kof** [comment] 2017-07-31 12:20
border is red in your example, and it says it should be red.

**Comment by mistadikay** [comment] 2017-07-31 12:28
when you change the value, it says it should be grey, but it stays red

**Comment by kof** [comment] 2017-07-31 12:57
I tried, you are not changing the isValid value, how about using console.log(isValid)?

**Comment by kof** [comment] 2017-07-31 12:58
No I was wrong, you do, .update is not working in this case.

**Comment by kof** [comment] 2017-07-31 13:12
Strange, it is reproducible without jss-nested as well. https://www.webpackbin.com/bins/-KqNhpnr4ZAJ82kywzI2

**Comment by iamstarkov** [comment] 2017-08-04 10:06
what do we do?

**Comment by kof** [comment] 2017-08-04 10:07
Need to reproduce iit with a test and fix, if you are interested I can handle it over to you

**Comment by kof** [comment] 2017-08-04 10:09
Just looked at it again, we forgot to add option link: true, now it  works https://www.webpackbin.com/bins/-KqNhpnr4ZAJ82kywzI2

**Comment by kof** [comment] 2017-08-04 10:13
So the issue is related to that `:not`thing, if you use just '&' it works.

**Comment by kof** [comment] 2017-08-04 10:15
`:not(.bla)&`  works as well, so it is because of `#\\20`

**Comment by kof** [comment] 2017-08-04 10:19
I have a suspicion that we are not linking correctly the css rule and jss rule because of escapings, because they don't match

**Comment by kof** [comment] 2017-08-04 10:25
tbc https://github.com/cssinjs/jss/issues/557

**Comment by iamstarkov** [comment] 2017-08-10 14:49
in short: the rabbit hole is quite deep

**Comment by kof** [comment] 2017-08-10 14:51
should be fixed in jss@9.0.0-pre.1 @mistadikay let me know

**Comment by mistadikay** [comment] 2017-08-10 15:20
doesn't look like it? But I'm not sure how to test it without involving `jss-nested` [https://www.webpackbin.com/bins/-KqNVNfzLuuYxwDi5cY_](https://www.webpackbin.com/bins/-KqNVNfzLuuYxwDi5cY_)

**Comment by kof** [comment] 2017-08-10 18:51
You bin link didn't load, I tested here, works for me https://www.webpackbin.com/bins/-KqgiTDVbilzhS2C8xaD

**Comment by mistadikay** [comment] 2017-08-10 20:49
Github lost underscore from the link. 🙄  Fixed.

I noticed you're passing `{link: true}` as a second argument to `createStyleSheet` — what is it?

**Comment by kof** [comment] 2017-08-10 20:55
http://cssinjs.org/js-api?v=v9.0.0-pre.1#create-style-sheet

It is required to be true in order to activate function values right now. Not sure if we should change that in the future but lets discuss that in a separate issue.

**Comment by mistadikay** [comment] 2017-08-10 21:01
I guess it's going to be turned on by default in `react-jss`?

**Comment by kof** [comment] 2017-08-10 21:01
For dynamic sheets yes.

**Comment by kof** [comment] 2017-08-25 07:29
folow this one https://github.com/cssinjs/jss/issues/557

**Closed as completed by kof** 2017-08-25 07:29 UTC
